model_module = "model_impl.movie"
model_class = "Movie"
model_list_class = "MoviesList"
host = "http://localhost"
port = 8080
[apis]
get = "/movies/"
put = "/movies/"
post = "/movies/"
delete = "/movies/"