[model]
module = "impl.movie"
class = "Movie"

[model_list]
module = "impl.movie"
class = "MoviesList"

[request]
module = "base.request_handler"
class = "RequestHandler"

[apis]
host = "http://localhost"
port = 8080
get = "/movies/"
put = "/movies/"
post = "/movies/"
delete = "/movies/"