[model]
module = "impl.movie"
class = "Movie"

[model_list]
module = "impl.movie"
class = "MoviesList"

[model_version]
module = "impl.movie"
class = "MovieVersion"

[request]
module = "base.request_handler"
class = "RequestHandler"

[apis]
host = "http://localhost"
port = 8080
[apis.movies]
get = "/movies/"
put = "/movies/"
post = "/movies/"
delete = "/movies/"

[apis.movies_version]
get = "/movie_audit/"