name = "movies"

[model]
module = "impl.movie"
class = "Movie"

[model_list]
module = "impl.movie"
class = "MoviesList"

[model_audit]
module = "impl.movie"
class = "MovieAudit"

[apis]
host = "https://localhost"
port = 8443

[request]
module = "base.request_handler"
class = "RequestHandler"

[apis.model]
get = "/api/movies/"
put = "/api/movies/"
post = "/api/movies/"
delete = "/api/movies/"

[apis.model_audit]
get = "/api/movies-audit/"