name = "movies"

[model]
module = "impl.movie"
class = "Movie"

[model_list]
module = "impl.movie"
class = "MoviesList"

[model_audit]
module = "impl.movie"
class = "MovieAudit"

[request]
module = "base.request_handler"
class = "RequestHandler"

[apis]
host = "http://localhost"
port = 8080

[apis.model]
get = "/movies/"
put = "/movies/"
post = "/movies/"
delete = "/movies/"

[apis.model_audit]
get = "/movie_audit/"