name = "super_hero"

[model]
module = "impl.super_hero"
class = "SuperHero"

[model_list]
module = "impl.super_hero"
class = "SuperHeroList"

[model_audit]
module = "impl.super_hero"
class = "SuperHeroAudit"

[apis]
host = "http://localhost"
port = 8080

[request]
module = "base.request_handler"
class = "RequestHandler"

[apis.model]
get = "/super_hero/"
put = "/super_hero/"
post = "/super_hero/"
delete = "/super_hero/"

[apis.model_audit]
get = "/super_hero_audit/"