name = "super_hero"

[model]
module = "impl.super_hero"
class = "SuperHero"

[model_list]
module = "impl.super_hero"
class = "SuperHeroList"

[model_audit]
module = "impl.super_hero"
class = "SuperHeroAudit"

[apis]
host = "https://localhost"
port = 8443

[request]
module = "impl.super_hero_request_handler"
class = "SuperHeroJsonRequestHandler"

[apis.model]
get = "/api/superhero/"
put = "/api/superhero/"
post = "/api/superhero/"
delete = "/api/superhero/"

[apis.model_audit]
get = "/api/superhero/all/"